# -*- Python -*-

Import('env', 'DirHeaders')

sources = [
    'GGColorDlg.cpp',
    'GGFileDlg.cpp',
    'GGThreeButtonDlg.cpp'
    ]

headers = ['dialogs'] + DirHeaders('../../include/dialogs')

if env['dynamic']:
    objects = env.SharedObject(sources)
else:
    objects = env.Object(sources)

Return('objects', 'sources', 'headers')
