# -*- Python -*-

Import('gigi_env')

sources = [
    'ColorDlg.cpp',
    'FileDlg.cpp',
    'ThreeButtonDlg.cpp'
    ]

if gigi_env['dynamic']:
    objects = gigi_env.SharedObject(sources)
else:
    objects = gigi_env.Object(sources)

Return('objects', 'sources')
