# -*- Python -*-

Import('env')

sources = [
    'ColorDlg.cpp',
    'FileDlg.cpp',
    'ThreeButtonDlg.cpp'
    ]

if env['dynamic']:
    objects = env.SharedObject(sources)
else:
    objects = env.Object(sources)

Return('objects', 'sources')
