# -*- Python -*-

Import('ogre_env')

def PluginName(name):
    return 'GiGiOgrePlugin_' + name

common_sources = [
    'OgreGUIInputPlugin.cpp'
    ]

sources = {}
objects = {}


# OIS plugin
if ogre_env['build_ogre_ois_plugin']:
    OIS_plugin_name = PluginName('OIS')
    ois_souces = [
        'OISInput.cpp'
        ]
    sources[OIS_plugin_name] = common_sources + ois_souces
    if ogre_env['dynamic']:
        objects[OIS_plugin_name] = ogre_env.SharedObject(sources[OIS_plugin_name])
    else:
        objects[OIS_plugin_name] = ogre_env.Object(sources[OIS_plugin_name])


Return('objects', 'sources')
