# -*- Python -*-

Import('ogre_plugin_envs')

common_sources = [
    'OgreGUIInputPlugin.cpp'
    ]

sources = {}
objects = {}


for key, value in ogre_plugin_envs.items():
    plugin_souces = [
        key + 'Input.cpp'
        ]
    sources[key] = common_sources + plugin_souces
    if value['dynamic']:
        objects[key] = value.SharedObject(sources[key])
    else:
        objects[key] = value.Object(sources[key])


Return('objects', 'sources')
