# -*- Python -*-

Import('net_env')

sources = [
    'SDLnet.c',
    'SDLnetTCP.c',
    'SDLnetUDP.c',
    'SDLnetselect.c',
    'fastevents.c',
    'net2.c',
    'trace.c'
    ]

if net_env['dynamic']:
    objects = net_env.SharedObject(sources)
else:
    objects = net_env.Object(sources)

Return('objects', 'sources')
