# -*- Python -*-

Import('net_env')

if net_env['with_builtin_sdlnet']:
    sources = [
        'SDLnet.c',
        'SDLnetTCP.c',
        'SDLnetUDP.c',
        'SDLnetselect.c'
        ]
    headers = [
        'net',
        'SDL_net.h',
        'SDLnetsys.h'
        ]
else:
    sources = []
    headers = ['net']

sources += [
    'fastevents.c',
    'net2.c',
    'trace.c'
    ]

headers += [
    'fastevents.h',
    'net2.h',
    'queue.h',
    'trace.h'
    ]

if net_env['dynamic']:
    objects = net_env.SharedObject(sources)
else:
    objects = net_env.Object(sources)

Return('objects', 'headers')
