# -*- Python -*-

Import('sdl_env', 'DirHeaders')

sources = [
    'SDLGGApp.cpp'
    ]

headers = ['SDL'] + DirHeaders('../../include/SDL')

if sdl_env['dynamic']:
    objects = sdl_env.SharedObject(sources)
else:
    objects = sdl_env.Object(sources)

Return('objects', 'headers')
