# -*- Python -*-

Import('sdl_env')

sources = [
    'SDLGUI.cpp'
    ]

if sdl_env['dynamic']:
    objects = sdl_env.SharedObject(sources)
else:
    objects = sdl_env.Object(sources)

Return('objects', 'sources')
