# -*- Python -*-

Import('env')

sources = [
    'ltdl.c'
    ]

if env['dynamic']:
    objects = env.SharedObject(sources, CPPDEFINES = env['libltdl_defines'])
else:
    objects = env.Object(sources, CPPDEFINES = env['libltdl_defines'])

Return('objects', 'sources')
