# -*- Python -*-

Import('env', 'DirHeaders')

sources = [
    'GGApp.cpp',
    'GGBrowseInfoWnd.cpp',
    'GGButton.cpp',
    'GGClr.cpp',
    'GGControl.cpp',
    'GGDrawUtil.cpp',
    'GGDropDownList.cpp',
    'GGDynamicGraphic.cpp',
    'GGEdit.cpp',
    'GGEventPump.cpp',
    'GGFont.cpp',
    'GGLayout.cpp',
    'GGListBox.cpp',
    'GGMenu.cpp',
    'GGMultiEdit.cpp',
    'GGPluginInterface.cpp',
    'GGPtRect.cpp',
    'GGScroll.cpp',
    'GGSlider.cpp',
    'GGStaticGraphic.cpp',
    'GGTextControl.cpp',
    'GGTexture.cpp',
    'GGWnd.cpp',
    'GGWndEditor.cpp',
    'GGZList.cpp',
    'XMLDoc.cpp'
    ]

headers = [None] + DirHeaders('../include')

if env['need__vsnprintf_c']:
    sources.append('_vsnprintf.c')

if env['dynamic']:
    objects = env.SharedObject(sources)
else:
    objects = env.Object(sources)

result_objects, result_sources, result_headers = SConscript('dialogs/SConscript', exports = ['env'])
objects += result_objects
sources += result_sources
headers.append(result_headers)

Return('objects', 'sources', 'headers')
