# -*- Python -*-

Import('gigi_env')

sources = [
    'AlignmentFlags.cpp',
    'Base.cpp',
    'BrowseInfoWnd.cpp',
    'Button.cpp',
    'Clr.cpp',
    'Control.cpp',
    'Cursor.cpp',
    'DrawUtil.cpp',
    'DropDownList.cpp',
    'DynamicGraphic.cpp',
    'Edit.cpp',
    'EventPump.cpp',
    'Font.cpp',
    'GUI.cpp',
    'Layout.cpp',
    'ListBox.cpp',
    'Menu.cpp',
    'MultiEdit.cpp',
    'PluginInterface.cpp',
    'PtRect.cpp',
    'Scroll.cpp',
    'Slider.cpp',
    'StaticGraphic.cpp',
    'StyleFactory.cpp',
    'TabWnd.cpp',
    'TextControl.cpp',
    'Texture.cpp',
    'Timer.cpp',
    'Wnd.cpp',
    'WndEditor.cpp',
    'WndEvent.cpp',
    'ZList.cpp'
    ]

if gigi_env['need__vsnprintf_c']:
    sources.append('_vsnprintf.c')

if gigi_env['dynamic']:
    objects = gigi_env.SharedObject(sources)
else:
    objects = gigi_env.Object(sources)

result_objects, result_sources = SConscript('dialogs/SConscript', exports = ['gigi_env'])
objects += result_objects
sources += result_sources

Return('objects', 'sources')
